### ISSUE TITLE
ISSUE-2596: Enable `isForceGCAllowWhenNoSpace` for the DBLedgerStorage

### ISSUE THREAD

**Issue by sijie** [streamnative/bookkeeper#328]
Original Issue: apache/bookkeeper#2596 

---

**FEATURE REQUEST**

1. Please describe the feature you are requesting.

In some cases, users disabled the topic compaction task to reduce the I/O load, this will also make the write latency more stable(I/O resource competition). I have checked the source code of the BookKeeper, I think the `isForceGCAllowWhenNoSpace` does not work for the DBLedgerStorage(the default value of Pulsar). Currently, the behavior of the `isForceGCAllowWhenNoSpace` is It is a disk listener to decide whether to start the compaction task while the disk of the Ledger almost full. It should be the same behavior when we call `gc` endpoint manually.

**Comment by zymap** [comment]
- [ ] Allow force compact entry log when disabling entrh log compaction https://github.com/apache/bookkeeper/pull/2626
