### ISSUE TITLE
ISSUE-1979: Broken "metrics" link in documentation

### ISSUE THREAD

**Issue by sijie** [streamnative/bookkeeper#56]
Original Issue: apache/bookkeeper#1979 

---

**BUG REPORT**

***Describe the bug***

The [`metrics.md`](https://github.com/apache/bookkeeper/blob/28dee8464764b0edceeb31ce24424f0947b5789b/site/docs/4.7.1/admin/metrics.md) file has a broken link pointing to an unknown site:
> For a full listing of available metrics, see the [Metrics](https://github.com/apache/bookkeeper/blob/28dee8464764b0edceeb31ce24424f0947b5789b/site/docs/reference/metrics) reference doc. <- (broken link)

This problem is also visible in the documentation page: https://bookkeeper.apache.org/docs/4.7.3/reference/metrics

***To Reproduce***

Just click the link posted above, you should see the problem.

***Expected behavior***

A "Metrics" page is expected with all the metrics that Bookkeeper exposes.

***Screenshots***

n/a.

***Additional context***

n/a.

**Comment by Jennifer88huang** [comment]
what's the status of this issue?

**Comment by sijia-w** [comment]
@Jennifer88huang  The links are updated. But still some difficulties with committing my changes.

**Comment by sijia-w** [comment]
remote: Permission to apache/bookkeeper.git denied to sijia-w.
fatal: unable to access 'https://github.com/apache/bookkeeper/': The requested URL returned error: 403

**Comment by sijia-w** [comment]
The pr to fix this issue is: https://github.com/streamnative/bookkeeper/pull/225

**Comment by sijia-w** [comment]
The issue was fixed by https://github.com/apache/bookkeeper/pull/2400. The previous pr was closed because it was from master.
